### PR TITLE
FOGL-2441: added displayName and readonly to config items

### PR DESCRIPTION
**Pull request by pintomax**
FOGL-2441: added displayName and readonly to config items

Added a check for Python script name containing string SCRIPT_NAME (notify35)

Method notify35 is checked after loading the Python module.

Any Python error or method not existent will cause plugin_init to return NULL

### CODE REVIEW

**Comment by praveen-garg** [comment]
@mshariq-nerd  could you please help reviewing and  testing?

**Comment by pintomax** [comment]
@mshariq-nerd "Space in notification name" looks like a bug, not sure we already have a task for it

**Comment by pintomax** [comment]
@mshariq-nerd "Description field value is not updating while creating the notification", it looks like a bug.

Is the change here for file name ok for you?

**Comment by mshariq-nerd** [comment]
> Is the change here for file name ok for you?

Right now user not getting any information about failed contract.  we should log a proper warning and reason in syslog that contract failed in case of mismatch file and method name while uploading the script. 

> "Space in notification name" looks like a bug, not sure we already have a task for it

Yes we have a ticket [FOGL-2434](https://scaledb.atlassian.net/browse/FOGL-2434) for this issue

> "Description field value is not updating while creating the notification", it looks like a bug.
I will create a ticket for this

**Comment by pintomax** [comment]
@mshariq-nerd Thanks for your comments.

I'll re-check again the logging of wrong file name being updated.

**Comment by pintomax** [comment]
@mshariq-nerd This notify plugin is missing the plugin_reconfigure entry point.

When you disable an available notification instance and then re-enable it you will see the WARN message.

You don't see the WARN message every time you update the script due to  missing the plugin_reconfigure entry point.

I suggest creating a task for "missing the plugin_reconfigure entry point." and make this FOGL-2441 dependent on the new issue.

**Comment by pintomax** [comment]
FOGL-2523 crated: Add missing "plugin_reconfigure" entry point to notify-python35 delivery plugin

**Comment by mshariq-nerd** [comment]
After disable an available notification instance and then re-enable it you will see the WARN message.

- In case of invalid method name inside python35.py file, warning message in syslog
```
NotificationServer[21474]: INFO: Configuration change notification for TEST_ONE
Feb 26 11:47:16  NotificationServer[21474]: INFO: Enabling notification instance 'TEST_ONE'
Feb 26 11:47:16  NotificationServer[21474]: INFO: Loading delivery plugin 'python35'.
Feb 26 11:47:16  NotificationServer[21474]: INFO: Loaded delivery plugin 'python35'.
Feb 26 11:47:16  NotificationServer[21474]: FATAL: Notification plugin 'python35', Error 'no description'
Feb 26 11:47:16  NotificationServer[21474]: FATAL: Notification plugin python35 (deliveryTEST_ONE) error: cannot find Python 3.5 method 'notify35' in loaded module 'deliverytest_one_script_notify35.py'
Feb 26 11:47:16  NotificationServer[21474]: INFO: No triggers set for OverMaxRule plugin
Feb 26 11:47:16  NotificationServer[21474]: INFO: Succesfully enabled notification instance 'TEST_ONE'
```

-  In case of invalid module name e.g. demo.py, warning message in syslog
```
INFO: Configuration change notification for TEST_ONE
Feb 26 11:51:03 NotificationServer[21474]: INFO: Enabling notification instance 'TEST_ONE'
Feb 26 11:51:03 NotificationServer[21474]: INFO: Loading delivery plugin 'python35'.
Feb 26 11:51:03 NotificationServer[21474]: INFO: Loaded delivery plugin 'python35'.
Feb 26 11:51:04 NotificationServer[21474]: WARNING: Notification plugin 'python35', called Python 3.5 script name 'deliverytest_one_script_demo' does not end with name 'notify35'. Check 'script' item in 'deliveryTEST_ONE' configuration. Notification plugin has been disabled.
```

-  [FOGL-2528](https://scaledb.atlassian.net/browse/FOGL-2528) logged for  `Description field value is not updating while creating the notification`

**Pull request merged**
